# Generated by Django 4.0 on 2023-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0002_remove_category_image_remove_phone_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='phone/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='image2',
            field=models.ImageField(default=1, upload_to='phone/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='image3',
            field=models.ImageField(default=1, upload_to='phone/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='image4',
            field=models.ImageField(default=1, upload_to='phone/images'),
            preserve_default=False,
        ),
    ]
