# Generated by Django 4.0 on 2023-04-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phonenumber',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
