# Generated by Django 4.0 on 2023-05-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0005_phone_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image2',
            field=models.ImageField(null=True, upload_to='phone/images'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image3',
            field=models.ImageField(null=True, upload_to='phone/images'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image4',
            field=models.ImageField(null=True, upload_to='phone/images'),
        ),
    ]
