# Generated by Django 4.0 on 2023-05-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0007_alter_phone_image2_alter_phone_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image4',
        ),
        migrations.AlterField(
            model_name='phone',
            name='image2',
            field=models.ImageField(default=1, upload_to='phone/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='image3',
            field=models.ImageField(default=1, upload_to='phone/images'),
            preserve_default=False,
        ),
    ]
