# Generated by Django 4.0 on 2023-05-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0008_remove_phone_image4_alter_phone_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
