# Generated by Django 4.0 on 2023-05-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0009_phone_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='view_count',
        ),
    ]
