# Generated by Django 4.0 on 2023-05-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0010_remove_phone_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
