# Generated by Django 4.0 on 2023-05-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0012_remove_category_name_en_remove_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
