# Generated by Django 4.0 on 2023-05-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0014_category_parts_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_parts',
            name='image',
        ),
    ]
